// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9AusariKBVOiI2jRvs1aq922Tnf4y4A',
    appId: '1:588291779329:web:02f0fcd130cb43d3758900',
    messagingSenderId: '588291779329',
    projectId: 'sharsnet',
    authDomain: 'sharsnet.firebaseapp.com',
    storageBucket: 'sharsnet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWPesf-MshBsiBbZGY3jRmpOz0sP9zR68',
    appId: '1:588291779329:android:084748b0381341d1758900',
    messagingSenderId: '588291779329',
    projectId: 'sharsnet',
    storageBucket: 'sharsnet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI1GpjqRtbjBZ83Rqsowk64uAhnjDzzMw',
    appId: '1:588291779329:ios:22539fdaa80b0640758900',
    messagingSenderId: '588291779329',
    projectId: 'sharsnet',
    storageBucket: 'sharsnet.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI1GpjqRtbjBZ83Rqsowk64uAhnjDzzMw',
    appId: '1:588291779329:ios:22539fdaa80b0640758900',
    messagingSenderId: '588291779329',
    projectId: 'sharsnet',
    storageBucket: 'sharsnet.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT9AusariKBVOiI2jRvs1aq922Tnf4y4A',
    appId: '1:588291779329:web:9c7365500a022d10758900',
    messagingSenderId: '588291779329',
    projectId: 'sharsnet',
    authDomain: 'sharsnet.firebaseapp.com',
    storageBucket: 'sharsnet.appspot.com',
  );
}
